kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/component: ingress-controller
    app.kubernetes.io/version: "0.1"
    app.kubernetes.io/instance: traefik1
    app.kubernetes.io/part-of: "opa-demo"
    app.kubernetes.io/managed-by: "me-you-and-us"
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      containers:
        - image: traefik:1.7
          name: traefik-ingress-lb
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: httpn
              containerPort: 8880
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          args:
            - --configfile=/config/traefik.toml
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /acme
              name: acme
      volumes:
        - name: config
          configMap:
            name: traefik-config
        - name: acme
          persistentVolumeClaim:
            claimName: traefik-acme