kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: traefik-acme
  labels:
    app: traefik
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "1Gi"
  storageClassName: do-block-storage
