apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ImagesShouldMatch
metadata:
  name: imagesshouldmatch
spec:
  match:
    kinds:
      - apiGroups: ["extensions","apps"]
        kinds: ["Deployment"]
  parameters:
    imagesMatch:
      - "piotrjanik"