apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: opa
resources:
  - namespace.yaml
  - constraints
  - keycloak
  - frontend.yaml
  - enquiries.yaml
  - orders.yaml
  - policies.yml
  - ingress.yaml


configMapGenerator:
  - name: opa-config
    files:
      - opa-sidecar/config.yaml

patches:
  - path: opa-sidecar/patch-opa-sidecar.yaml
    target:
      kind: Deployment
      labelSelector: app.kubernetes.io/component=service